### ISSUE TITLE
Add autopan/autozoom params on QueryLayer control

### ISSUE THREAD

**Issue by nachouve** [IET-Xunta/XVM#31]
Add autopan/autozoom params on QueryLayer control.

The YAML file of the control which add the vector layer using QueryLayerControl may be :

``` yaml

init:
  displayClass: 'olControlSimpleForm'
  trigger: eval(launchSimpleFormDialog)
  title: eval($.i18n('buscador'))
  mylayer1:
    autozoom: false
    autopan: true
  mylayer2:
    autozoom: true
    autopan: true

```
